Repository Leafresh-2024/Leafresh-Frontend, pull requests merged in 2024-09, with the labels that each got.

#2 Leafresh/main components
  package-lock.json
  package.json
  src/App.vue
  src/assets/base.css
  src/assets/css/leafresh_fonts.css
  src/assets/css/reset.css
  src/assets/logo.svg
  src/assets/main.css
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/defaultComponents/defaultHeader.vue
  src/components/defaultComponents/defaultSection.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.js
  src/router/index.js
  src/stores/counter.js
  src/stores/mainStore.js
  src/views/AboutView.vue
  src/views/Community.vue
  src/views/GardenDiary.vue
  src/views/HomeView.vue
  src/views/PlantShare.vue
Labels: In development

#10 feat : login
  src/components/LoginForm.vue
  src/components/SignupForm.vue
  src/components/common/defaultHeader.vue
  src/router/index.js
  src/stores/useLoginState.js
  src/views/LoginView.vue
  src/views/SignupView.vue
Labels: enhancement

#11 chore : login modify
  src/components/common/defaultHeader.vue
Labels: duplicate, enhancement

#21 feat : env 전체 api 기본포트 설정
  src/components/SignupForm.vue
  src/components/common/defaultHeader.vue
  src/views/LoginView.vue
  src/views/MarketAddPost.vue
  src/views/SignupView.vue
Labels: Development completed

#22 design : 회원가입화면 수정
  src/views/SignupView.vue
Labels: duplicate

#23 feat : bootstrap, feed setting
  package-lock.json
  package.json
  src/components/gardenDiary/feed/feedCard.vue
  src/views/GardenDiary.vue
Labels: In development

#25 fix : bug fix
  src/components/common/defaultSection.vue
  src/components/feed/feedCard.vue
  src/views/GardenDiary.vue
Labels: Modification

#36 feat: add todo
  src/components/diary/diarySchedule.vue
  src/components/diary/todo.vue
Labels: In development

#51 Leafresh/main diary feed
  src/components/common/defaultHeader.vue
  src/components/feed/feedCard.vue
  src/stores/users.js
  src/views/GardenDiary.vue
Labels: In development

#53 Leafresh/main diary feed
  src/components/common/defaultHeader.vue
  src/components/feed/feedCard.vue
  src/components/feed/feedForm.vue
  src/main.js
  src/router/index.js
  src/stores/users.js
  src/views/FeedAdded.vue
  src/views/GardenDiary.vue
Labels: In development

#55 feat: todo
  package-lock.json
  src/assets/todo.js
  src/components/diary/calender.vue
  src/components/diary/diarySchedule.vue
  src/components/diary/todayTodo.vue
  src/components/diary/todo.vue
Labels: In development

#56 fix : header component fixed
  src/App.vue
  src/components/common/defaultHeader.vue
  src/components/feed/feedCard.vue
  src/views/GardenDiary.vue
Labels: Modification

#62 fix : user profile router fixed
  src/components/common/defaultHeader.vue
  src/views/ProfileRegistration.vue
Labels: Modification

#67 feat : leafresh info update
  src/assets/css/leafresh_scroll.css
  src/components/common/defaultHeader.vue
  src/main.js
  src/router/index.js
  src/views/LeafreshInfo.vue
Labels: In development

#70 fix: todolist
  package-lock.json
  package.json
  src/components/diary/diarySchedule.vue
  src/components/diary/todayTodo.vue
  src/components/diary/todoform.vue
  src/views/Community.vue
Labels: In development

#77 feat : weather api added
  src/components/common/defaultHeader.vue
  src/components/common/weather.vue
Labels: In development

#80 Leafresh/main components weather
  src/components/common/loading.vue
  src/views/LeafreshInfo.vue
Labels: Development completed

#83 fix : fix components
  src/components/common/defaultHeader.vue
  src/components/common/weather.vue
  src/views/Community.vue
Labels: Modification

#86 로그인 및 회원가입 페이지 수정
  package-lock.json
  package.json
  src/assets/css/sweetalert2.css
  src/assets/images/background.webp
  src/assets/images/background2.webp
  src/assets/js/todo.js
  src/components/LoginForm.vue
  src/components/common/defaultHeader.vue
  src/components/common/defaultSection.vue
  src/components/diary/diarySchedule.vue
  src/main.js
  src/router/index.js
  src/views/LoginView.vue
  src/views/SignupView.vue
Labels: Modification

#87 style : components fixed
  src/components/common/defaultSection.vue
  src/router/index.js
  src/views/LeafreshInfo.vue
Labels: Modification

#90 feat: checklist
  package-lock.json
  package.json
  src/components/diary/diaryCard.vue
  src/components/diary/diaryForm.vue
  src/components/diary/plantCare/Checklist.vue
  src/components/diary/plantCare/PlantInfo.vue
  src/components/diary/plantCare/plantCalendar.vue
  src/router/index.js
  src/stores/plantCareStore.js
  src/views/DiaryDetail.vue
Labels: In development

#93 fix : profile ffixed
  package-lock.json
  package.json
  src/components/diary/diaryProfile.vue
  src/components/feed/feedCard.vue
  src/main.js
  src/stores/users.js
  src/views/GardenDiary.vue
Labels: Modification

#94 feat: calendar and care
  src/components/diary/diaryCard.vue
  src/components/diary/plantCare/Checklist.vue
  src/components/diary/plantCare/plantCalendar.vue
  src/components/diary/plantCare/plantCarememo.vue
  src/stores/plantCareStore.js
  src/views/DiaryDetail.vue
Labels: In development

#98 fix : feed error fixed
  src/components/feed/feedCard.vue
  src/views/GardenDiary.vue
Labels: Modification

#100 fix : feed fixed
  src/components/common/weather.vue
  src/components/feed/feedCard.vue
  src/components/feed/feedForm.vue
  src/views/FeedAdded.vue
  src/views/FeedDetail.vue
  src/views/GardenDiary.vue
Labels: Modification

#104 fix : feed fixed
  src/components/feed/feedFixForm.vue
  src/components/feed/feedForm.vue
  src/router/index.js
  src/views/FeedAdded.vue
  src/views/FeedDetail.vue
  src/views/FeedFix.vue
Labels: Development completed

#105 fix: diaryTodo
  src/components/diary/diarySchedule.vue
  src/components/diary/todayTodo.vue
  src/components/diary/todo.vue
  src/components/diary/todoform.vue
  src/stores/todoStore.js
Labels: In development

#107 fix : components update
  src/components/common/defaultSection.vue
  src/components/common/weather.vue
  src/components/feed/feedCard.vue
  src/router/index.js
  src/views/FeedDetail.vue
Labels: Modification

#112 fix: back & delete todo
  src/components/diary/diarySchedule.vue
  src/components/diary/todayTodo.vue
  src/views/DiaryDetail.vue
Labels: In development

#119 feat : community update!!
  src/components/common/communityDetail.vue
  src/views/Community.vue
  src/views/LoginView.vue
  src/views/SignupView.vue
  src/views/TermsAgreementView.vue
Labels: In development

#121 fix : btn style fixed
  src/App.vue
  src/components/common/communityDetail.vue
Labels: Modification

#122 feat: plantCare add
  src/components/diary/calender.vue
  src/components/diary/diarySchedule.vue
  src/components/diary/plantCare/Checklist.vue
  src/components/diary/plantCare/PlantInfo.vue
  src/components/diary/plantCare/PlantcareForm.vue
  src/components/diary/plantCare/plantCalendar.vue
  src/components/diary/plantCare/plantCarememo.vue
  src/components/diary/todayTodo.vue
  src/stores/plantCareStore.js
  src/stores/todoStore.js
  src/views/DiaryDetail.vue
Labels: In development

#124 fix : form style
  src/components/feed/feedFixForm.vue
  src/components/feed/feedForm.vue
Labels: Modification

#126 style: css style update
  src/components/common/communityDetail.vue
  src/views/LeafreshInfo.vue
Labels: Modification

#138 feat: calendar&todo
  src/components/diary/diaryForm.vue
  src/components/diary/plantCare/PlantInfo.vue
  src/components/diary/plantCare/plantCalendar.vue
  src/components/diary/plantSchedule/calender.vue
  src/components/diary/plantSchedule/diarySchedule.vue
  src/components/diary/plantSchedule/todayTodo.vue
  src/stores/plantCareStore.js
  src/stores/users.js
  src/views/GardenDiary.vue
Labels: In development

#142 feat: PlantCare calendar icon fix
  src/components/diary/plantCare/Checklist.vue
  src/components/diary/plantCare/PlantInfo.vue
  src/components/diary/plantCare/PlantcareForm.vue
  src/components/diary/plantCare/plantCalendar.vue
  src/components/diary/plantSchedule/calender.vue
  src/components/diary/plantSchedule/diarySchedule.vue
  src/components/diary/plantSchedule/todayTodo.vue
  src/stores/plantCareStore.js
  src/stores/todoStore.js
Labels: In development

#145 fix: css Calendar
  package-lock.json
  package.json
  src/components/diary/plantCare/Checklist.vue
  src/main.js
  src/stores/plantCareStore.js
Labels: In development

#155 fix: check
  src/components/diary/plantCare/Checklist.vue
Labels: In development

#158 feat: plant get by userNickname
  src/components/diary/diaryCard.vue
  src/components/diary/plantSchedule/diarySchedule.vue
  src/stores/gardenStore.js
  src/views/GardenDiary.vue
  src/views/PlantAddModal.vue
Labels: In development

#162 fix: feed script
  src/views/DiaryDetail.vue
  src/views/FeedAdded.vue
  src/views/FeedDetail.vue
Labels: Modification

#171 fix: feed update
  src/components/feed/feedCard.vue
  src/components/feed/feedFixForm.vue
  src/components/feed/feedForm.vue
  src/stores/users.js
  src/views/FeedAdded.vue
  src/views/FeedDetail.vue
  src/views/LoginView.vue
Labels: Modification

#172 fix: detail author profileImg fixed
  src/views/FeedDetail.vue
Labels: Modification

#175 fix: feed and plant
  src/components/diary/diaryCard.vue
  src/components/feed/feedCard.vue
Labels: Modification

#176 fix: log deleted
  src/components/feed/feedCard.vue
Labels: Modification
